### ISSUE TITLE
CMC eth-usd rate

### ISSUE THREAD

**Issue by namnm1991** [KyberNetwork/reserve-data#445]
https://github.com/KyberNetwork/reserve-data/blob/e0c95e9bdf58568167292eda5155c0bfd1a981d9/common/blockchain/cmc_eth_usd_rate.go#L176

Realtime timepoint is set only one time. 

The reserve-data needs time to process trades which happen before realtime 
timepoint, let's call this duration D. 

For trades that happen between [realtime timepoint -> (realtime timepoint + D)], 
these trade will use realtime rate. It could be not good if D is big, 
because the realtime rate might not be the rate at trade's timepoint.

In general, it depends on D, if D is small as we process trades fast, we could 
ignore this problem. Otherwise, we could improve by update realtime timepoint
along with realtime rate.

**Comment by favadi** [comment]
close as removed CMC from core already.
